version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: sphinx_loongsonlab_theme/templates/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: sphinx_loongsonlab_theme/templates/source/conf.py

formats:
  - pdf